use managementoverview;
drop table tools;
drop table contacts;
drop table assets;
drop table skills;
drop table checks;
drop table events;
drop table cashflows;
drop table balance;
drop table stocks;
#drop table tasks;
#drop table kapital;
